name: 'Deploy'
on: ['push']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v1'
    
    - name: Install kubectl
      run: "sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2 && curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -"
    - run: "sudo echo 'deb https://apt.kubernetes.io/ kubernetes-xenial main' | sudo  tee -a /etc/apt/sources.list.d/kubernetes.list"
    - run: "sudo apt-get update && sudo apt-get install -y kubectl && mkdir ~/.kube"
    - shell: bash
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG" > ~/.kube/config
      
    - name: Install Helm
      run: "curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && chmod 700 get_helm.sh &&./get_helm.sh"

    - name: 'Helm Deploy'
      # Parameters are pulled directly from the GitHub deployment event so the
      # configuration for the job here is very minimal.
      run: helm upgrade --install --wait --namespace nha client-registry Charts/client-registry
